//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_NANO_SoC_GHRD(

    //////////// CLOCK //////////
    input               FPGA_CLK1_50,
    input               FPGA_CLK2_50,
    input               FPGA_CLK3_50,

    //////////// HPS //////////
    output   [14: 0]    HPS_DDR3_ADDR,
    output   [ 2: 0]    HPS_DDR3_BA,
    output              HPS_DDR3_CAS_N,
    output              HPS_DDR3_CK_N,
    output              HPS_DDR3_CK_P,
    output              HPS_DDR3_CKE,
    output              HPS_DDR3_CS_N,
    output   [ 3: 0]    HPS_DDR3_DM,
    inout    [31: 0]    HPS_DDR3_DQ,
    inout    [ 3: 0]    HPS_DDR3_DQS_N,
    inout    [ 3: 0]    HPS_DDR3_DQS_P,
    output              HPS_DDR3_ODT,
    output              HPS_DDR3_RAS_N,
    output              HPS_DDR3_RESET_N,
    input               HPS_DDR3_RZQ,
    output              HPS_DDR3_WE_N,

    //////////// LED //////////
    output   [ 7: 0]    LED
);

//=======================================================
//  REG/WIRE declarations
//=======================================================
wire hps_fpga_reset_n;
wire        fpga_clk_50;
wire [63:0] adder_a_export;
wire [63:0] adder_b_export;
wire [63:0] adder_sum_export;

assign fpga_clk_50 = FPGA_CLK1_50;

//=======================================================
//  Memory Subsystem (replaces fpmult)
//=======================================================

// Trace input assembled from the two 64-bit PIOs
// trace_line[120:0] = { adder_b[56:0] , adder_a[63:0] }
wire [120:0] trace_line = {adder_b_export[56:0], adder_a_export[63:0]};

// Observation / debug signals
wire obs_tlb_req, obs_cache_req, obs_cache_we;
wire [29:0] obs_cache_paddr;
wire [63:0] obs_cache_wdata;
wire obs_cache_ret_valid;
wire [63:0] obs_cache_ret_data;
wire obs_l2_req_valid;
wire [29:0] obs_l2_req_addr;
wire obs_wb_valid;
wire [29:0] obs_wb_addr;

// ── Sticky status register ───────────────────────────────────────────────
// obs_l2_req_valid, obs_wb_valid, and obs_cache_ret_valid are single-cycle
// pulses at 50 MHz (20 ns).  The HPS polls at ms intervals and can never
// catch a 1-cycle event via a combinational wire.  So we latch them here:
//   bit 63     : ever saw a cache_ret_valid (L1 returned data to LSQ)
//   bit 62     : ever saw obs_l2_req_valid  (L1 had a cache miss → L2)
//   bit 61     : ever saw obs_wb_valid      (L1 wrote back dirty line)
//   bit 60     : ever saw l2_ext_rd_req     (L2 miss → DDR3 fetch)
//   bit 59     : ever saw avm_read asserted (Avalon master started DDR3 read)
//   bit 58     : ever saw !avm_waitrequest while avm_read (bridge accepted beat)
//   bit 57     : ever saw avm_readdatavalid (bridge returned data)
//   bits 56:30 : obs_wb_addr[26:0] latched at last wb_valid pulse
//   bits 29:0  : obs_cache_ret_data[29:0] latched at last cache_ret_valid
//
// Clear all sticky bits by writing 0xFFFFFFFF_FFFFFFFF to adder_b (the
// "all-ones" sentinel is never a valid trace packet because op=7,id=15 is
// the NOP sentinel with value_valid=1 and all value bits set, which is
// distinguishable; the clear fires when adder_b[63:57] == 7'b1111111).
reg [63:0] status_sticky;
wire clear_status = (adder_b_export[63:57] == 7'b1111111);

always @(posedge fpga_clk_50 or negedge hps_fpga_reset_n) begin
    if (!hps_fpga_reset_n) begin
        status_sticky <= 64'h0;
    end else if (clear_status) begin
        status_sticky <= 64'h0;
    end else begin
        if (obs_cache_ret_valid) begin
            status_sticky[63]    <= 1'b1;
            status_sticky[29:0]  <= obs_cache_ret_data[29:0];
        end
        if (obs_l2_req_valid) begin
            status_sticky[62]    <= 1'b1;
        end
        if (obs_wb_valid) begin
            status_sticky[61]    <= 1'b1;
            status_sticky[56:30] <= obs_wb_addr[26:0];
        end
        if (l2_ext_rd_req) begin
            status_sticky[60]    <= 1'b1;
        end
        // Avalon DDR3 path diagnostics
        if (avm_read) begin
            status_sticky[59]    <= 1'b1;
        end
        if (avm_read && !avm_waitrequest) begin
            status_sticky[58]    <= 1'b1;
        end
        if (avm_readdatavalid) begin
            status_sticky[57]    <= 1'b1;
        end
    end
end

assign adder_sum_export = status_sticky;

// ── Cache-level LED indicators ───────────────────────────────────────────
// After a memory request completes, show which level served it:
//   LED[0] = L1 hit   (data was in L1 cache)
//   LED[1] = L2 hit   (L1 missed, L2 had it)
//   LED[2] = DDR3     (both L1 and L2 missed, fetched from DDR3)
//   LED[7] = heartbeat (~1 Hz blink, shows FPGA is alive)
//
// LEDs are held for 0.5 seconds so the result is visible.
reg       saw_l2_req;
reg       saw_ddr3_req;
reg [2:0] led_level;
reg [24:0] led_hold;
localparam [24:0] LED_HOLD_TIME = 25'd25_000_000; // 0.5s at 50 MHz

always @(posedge fpga_clk_50 or negedge hps_fpga_reset_n) begin
    if (!hps_fpga_reset_n) begin
        saw_l2_req   <= 1'b0;
        saw_ddr3_req <= 1'b0;
        led_level    <= 3'b000;
        led_hold     <= 25'd0;
    end else if (clear_status) begin
        saw_l2_req   <= 1'b0;
        saw_ddr3_req <= 1'b0;
        led_level    <= 3'b000;
        led_hold     <= 25'd0;
    end else begin
        // Track L1 miss (→ L2 request)
        if (obs_l2_req_valid)
            saw_l2_req <= 1'b1;

        // Track L2 miss (→ DDR3 request)
        if (l2_ext_rd_req)
            saw_ddr3_req <= 1'b1;

        // When data returns, classify and light LED
        if (obs_cache_ret_valid) begin
            if (!saw_l2_req)
                led_level <= 3'b001;   // L1 hit
            else if (!saw_ddr3_req)
                led_level <= 3'b010;   // L2 hit
            else
                led_level <= 3'b100;   // DDR3 fetch

            led_hold     <= LED_HOLD_TIME;
            saw_l2_req   <= 1'b0;
            saw_ddr3_req <= 1'b0;
        end

        // Countdown hold timer
        if (led_hold > 25'd0)
            led_hold <= led_hold - 25'd1;
    end
end

// Heartbeat on LED[7] (~1 Hz blink)
reg [25:0] heartbeat_cnt;
always @(posedge fpga_clk_50 or negedge hps_fpga_reset_n) begin
    if (!hps_fpga_reset_n) heartbeat_cnt <= 26'd0;
    else                   heartbeat_cnt <= heartbeat_cnt + 26'd1;
end

assign LED[0] = (led_hold > 25'd0) ? led_level[0] : 1'b0;  // L1 hit
assign LED[1] = (led_hold > 25'd0) ? led_level[1] : 1'b0;  // L2 hit
assign LED[2] = (led_hold > 25'd0) ? led_level[2] : 1'b0;  // DDR3
assign LED[3] = 1'b0;
assign LED[4] = 1'b0;
assign LED[5] = 1'b0;
assign LED[6] = 1'b0;
assign LED[7] = heartbeat_cnt[25];  // ~1 Hz heartbeat

// L2 <-> Avalon memory master wires
wire         l2_ext_rd_req;
wire [23:0]  l2_ext_rd_addr;
wire         l2_ext_rd_valid;
wire [511:0] l2_ext_rd_data;
wire         l2_ext_wr_req;
wire [23:0]  l2_ext_wr_addr;
wire [511:0] l2_ext_wr_data;
wire         l2_ext_wr_done;
wire         l2_ext_busy;

// Avalon-MM master wires (64-bit, connect to fpga_mem on soc_system)
wire [31:0]  avm_address;
wire         avm_read;
wire [63:0]  avm_readdata;
wire         avm_readdatavalid;
wire         avm_write;
wire [63:0]  avm_writedata;
wire [7:0]   avm_byteenable;
wire         avm_waitrequest;

// Memory hierarchy: LSQ -> TLB -> L1 -> L2
top_with_L1 #(
    .USE_REAL_L2(1'b1),
    .USE_AVALON(1'b1),
    .L2_SETS(4)
) mem_subsystem (
    .clk(fpga_clk_50),
    .rst_n(hps_fpga_reset_n),
    .trace_line(trace_line),
    .obs_tlb_req(obs_tlb_req),
    .obs_cache_req(obs_cache_req),
    .obs_cache_we(obs_cache_we),
    .obs_cache_paddr(obs_cache_paddr),
    .obs_cache_wdata(obs_cache_wdata),
    .obs_cache_ret_valid(obs_cache_ret_valid),
    .obs_cache_ret_data(obs_cache_ret_data),
    .obs_l2_req_valid(obs_l2_req_valid),
    .obs_l2_req_addr(obs_l2_req_addr),
    .obs_wb_valid(obs_wb_valid),
    .obs_wb_addr(obs_wb_addr),
    .ext_mem_rd_req(l2_ext_rd_req),
    .ext_mem_rd_addr(l2_ext_rd_addr),
    .ext_mem_rd_valid(l2_ext_rd_valid),
    .ext_mem_rd_data(l2_ext_rd_data),
    .ext_mem_wr_req(l2_ext_wr_req),
    .ext_mem_wr_addr(l2_ext_wr_addr),
    .ext_mem_wr_data(l2_ext_wr_data),
    .ext_mem_wr_done(l2_ext_wr_done),
    .ext_mem_busy(l2_ext_busy)
);

// Avalon-MM master: 8 x 64-bit beats per 512-bit cache line
avalon_mem_master avm_master (
    .clk(fpga_clk_50),
    .rst_n(hps_fpga_reset_n),
    .mem_rd_req(l2_ext_rd_req),
    .mem_rd_addr(l2_ext_rd_addr),
    .mem_rd_valid(l2_ext_rd_valid),
    .mem_rd_data(l2_ext_rd_data),
    .mem_wr_req(l2_ext_wr_req),
    .mem_wr_addr(l2_ext_wr_addr),
    .mem_wr_data(l2_ext_wr_data),
    .mem_wr_done(l2_ext_wr_done),
    .mem_busy(l2_ext_busy),
    .avm_address(avm_address),
    .avm_read(avm_read),
    .avm_readdata(avm_readdata),
    .avm_readdatavalid(avm_readdatavalid),
    .avm_write(avm_write),
    .avm_writedata(avm_writedata),
    .avm_byteenable(avm_byteenable),
    .avm_waitrequest(avm_waitrequest)
);

//=======================================================
//  Structural coding
//=======================================================
soc_system u0(
               // 64-bit PIOs (trace input / status output)
               .adder_a_export(adder_a_export),
               .adder_b_export(adder_b_export),
               .adder_sum_export(adder_sum_export),
               // FPGA -> DDR3 Avalon-MM path (via fpga_mem_bridge)
               .fpga_mem_address(avm_address),
               .fpga_mem_read(avm_read),
               .fpga_mem_readdata(avm_readdata),
               .fpga_mem_readdatavalid(avm_readdatavalid),
               .fpga_mem_write(avm_write),
               .fpga_mem_writedata(avm_writedata),
               .fpga_mem_byteenable(avm_byteenable),
               .fpga_mem_waitrequest(avm_waitrequest),
               .fpga_mem_burstcount(1'b1),
               .fpga_mem_debugaccess(1'b0),
               //Clock&Reset
               .clk_clk(FPGA_CLK1_50),
               .reset_reset_n(hps_fpga_reset_n),
               //HPS ddr3
               .memory_mem_a(HPS_DDR3_ADDR),
               .memory_mem_ba(HPS_DDR3_BA),
               .memory_mem_ck(HPS_DDR3_CK_P),
               .memory_mem_ck_n(HPS_DDR3_CK_N),
               .memory_mem_cke(HPS_DDR3_CKE),
               .memory_mem_cs_n(HPS_DDR3_CS_N),
               .memory_mem_ras_n(HPS_DDR3_RAS_N),
               .memory_mem_cas_n(HPS_DDR3_CAS_N),
               .memory_mem_we_n(HPS_DDR3_WE_N),
               .memory_mem_reset_n(HPS_DDR3_RESET_N),
               .memory_mem_dq(HPS_DDR3_DQ),
               .memory_mem_dqs(HPS_DDR3_DQS_P),
               .memory_mem_dqs_n(HPS_DDR3_DQS_N),
               .memory_mem_odt(HPS_DDR3_ODT),
               .memory_mem_dm(HPS_DDR3_DM),
               .memory_oct_rzqin(HPS_DDR3_RZQ),
               .hps_0_h2f_reset_reset_n(hps_fpga_reset_n)
           );

endmodule