//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_NANO_SoC_GHRD(

    //////////// CLOCK //////////
    input               FPGA_CLK1_50,
    input               FPGA_CLK2_50,
    input               FPGA_CLK3_50,

    //////////// HPS //////////
    output   [14: 0]    HPS_DDR3_ADDR,
    output   [ 2: 0]    HPS_DDR3_BA,
    output              HPS_DDR3_CAS_N,
    output              HPS_DDR3_CK_N,
    output              HPS_DDR3_CK_P,
    output              HPS_DDR3_CKE,
    output              HPS_DDR3_CS_N,
    output   [ 3: 0]    HPS_DDR3_DM,
    inout    [31: 0]    HPS_DDR3_DQ,
    inout    [ 3: 0]    HPS_DDR3_DQS_N,
    inout    [ 3: 0]    HPS_DDR3_DQS_P,
    output              HPS_DDR3_ODT,
    output              HPS_DDR3_RAS_N,
    output              HPS_DDR3_RESET_N,
    input               HPS_DDR3_RZQ,
    output              HPS_DDR3_WE_N,

    //////////// LED //////////
    output   [ 7: 0]    LED
);

//=======================================================
//  REG/WIRE declarations
//=======================================================
wire hps_fpga_reset_n;
wire        fpga_clk_50;
wire [6:0]  fpga_led_internal;
wire [63:0] adder_a_export;
wire [63:0] adder_b_export;
wire [63:0] adder_sum_export;

wire [15:0] fpmult_p_out;
wire        fpmult_valid_out;
wire        fpmult_ready_out;
wire [3:0]  fpmult_oor_out;

assign fpga_clk_50 = FPGA_CLK1_50;

// Wire fpmult outputs into adder_sum_export:
// [15:0]  = fp result
// [19:16] = oor flags
// [20]    = valid
// [21]    = ready
// [63:22] = 0
assign adder_sum_export[15:0]  = fpmult_p_out;
assign adder_sum_export[19:16] = fpmult_oor_out;
assign adder_sum_export[20]    = fpmult_valid_out;
assign adder_sum_export[21]    = fpmult_ready_out;
assign adder_sum_export[63:22] = 42'b0;

fpmult #(.P(8), .Q(8)) my_fpmult (
    .rst_in_N  (hps_fpga_reset_n),
    .clk_in    (fpga_clk_50),
    .x_in      (adder_a_export[15:0]),
    .y_in      (adder_b_export[15:0]),
    .round_in  (2'b00),
    .start_in  (adder_a_export[16]),
    .p_out     (fpmult_p_out),
    .valid_out (fpmult_valid_out),
    .ready_out (fpmult_ready_out),
    .oor_out   (fpmult_oor_out)
);

//=======================================================
//  Structural coding
//=======================================================
soc_system u0(
               // Adder
               .adder_a_export(adder_a_export),
               .adder_b_export(adder_b_export),
               .adder_sum_export(adder_sum_export),
               //Clock&Reset
               .clk_clk(FPGA_CLK1_50),
               .reset_reset_n(hps_fpga_reset_n),
               //HPS ddr3
               .memory_mem_a(HPS_DDR3_ADDR),
               .memory_mem_ba(HPS_DDR3_BA),
               .memory_mem_ck(HPS_DDR3_CK_P),
               .memory_mem_ck_n(HPS_DDR3_CK_N),
               .memory_mem_cke(HPS_DDR3_CKE),
               .memory_mem_cs_n(HPS_DDR3_CS_N),
               .memory_mem_ras_n(HPS_DDR3_RAS_N),
               .memory_mem_cas_n(HPS_DDR3_CAS_N),
               .memory_mem_we_n(HPS_DDR3_WE_N),
               .memory_mem_reset_n(HPS_DDR3_RESET_N),
               .memory_mem_dq(HPS_DDR3_DQ),
               .memory_mem_dqs(HPS_DDR3_DQS_P),
               .memory_mem_dqs_n(HPS_DDR3_DQS_N),
               .memory_mem_odt(HPS_DDR3_ODT),
               .memory_mem_dm(HPS_DDR3_DM),
               .memory_oct_rzqin(HPS_DDR3_RZQ),
               .hps_0_h2f_reset_reset_n(hps_fpga_reset_n)
           );

assign LED = adder_sum_export[7:0];

endmodule